server:
  port: 3100

spring:
  application:
    name: config-server

  profiles:
    active: native, git

  cloud:
    config:
      server:
        native:
          search-locations: 'file:///Users/kimjiwon/Documents/msa-prc/project-configs'
        git:
          uri: https://github.com/JKjiwon/project-configs
          default-label: main
          search-paths:
            - configs
            - configs/*
          basedir: configs
          clone-on-start: true
eureka:
  instance:
    prefer-ip-address: false
    hostname: localhost

  client:
    register-with-eureka: true
    fetch-registry: true # 클라이언트 사이드 로드밸런싱을 위해, 유레카 정보를 다운 받는다.
    service-url:
      defaultZone: http://localhost:3150/eureka/